# Generated by Django 5.0.1 on 2025-11-05 15:57

import datetime
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="BarberScheduleSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "working_weekdays",
                    models.JSONField(
                        default=list,
                        help_text="Список номеров дней недели (0=пн, 6=вс)",
                        verbose_name="Рабочие дни недели",
                    ),
                ),
                (
                    "work_start_time",
                    models.TimeField(
                        default=datetime.time(9, 0), verbose_name="Время начала работы"
                    ),
                ),
                (
                    "work_end_time",
                    models.TimeField(
                        default=datetime.time(18, 0),
                        verbose_name="Время окончания работы",
                    ),
                ),
                (
                    "break_start_time",
                    models.TimeField(
                        blank=True, null=True, verbose_name="Время начала перерыва"
                    ),
                ),
                (
                    "break_end_time",
                    models.TimeField(
                        blank=True, null=True, verbose_name="Время окончания перерыва"
                    ),
                ),
                (
                    "slot_duration_minutes",
                    models.PositiveIntegerField(
                        default=30,
                        validators=[
                            django.core.validators.MinValueValidator(15),
                            django.core.validators.MaxValueValidator(240),
                        ],
                        verbose_name="Продолжительность сеанса (минуты)",
                    ),
                ),
                (
                    "booking_advance_days",
                    models.PositiveIntegerField(
                        default=14,
                        help_text="На сколько дней вперед клиенты могут записываться",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(90),
                        ],
                        verbose_name="Дней для открытия записи вперед",
                    ),
                ),
                (
                    "min_booking_notice_hours",
                    models.PositiveIntegerField(
                        default=2,
                        help_text="За сколько часов минимум нужно записываться",
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(72),
                        ],
                        verbose_name="Минимальное время уведомления (часы)",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Автоматическая генерация слотов включена",
                        verbose_name="Активно",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
                ),
                (
                    "barber",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="schedule_settings",
                        to="accounts.barberprofile",
                        verbose_name="Барбер",
                    ),
                ),
            ],
            options={
                "verbose_name": "Настройки расписания барбера",
                "verbose_name_plural": "Настройки расписаний барберов",
                "ordering": ["barber"],
            },
        ),
        migrations.CreateModel(
            name="Booking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "client_name",
                    models.CharField(max_length=100, verbose_name="Имя клиента"),
                ),
                (
                    "client_phone",
                    models.CharField(max_length=20, verbose_name="Телефон клиента"),
                ),
                (
                    "client_email",
                    models.EmailField(
                        blank=True,
                        max_length=254,
                        null=True,
                        verbose_name="Email клиента",
                    ),
                ),
                ("booking_date", models.DateField(verbose_name="Дата бронирования")),
                ("booking_start_time", models.TimeField(verbose_name="Время начала")),
                ("booking_end_time", models.TimeField(verbose_name="Время окончания")),
                (
                    "service_description",
                    models.TextField(
                        blank=True, null=True, verbose_name="Описание услуги"
                    ),
                ),
                (
                    "client_notes",
                    models.TextField(
                        blank=True, null=True, verbose_name="Заметки клиента"
                    ),
                ),
                (
                    "barber_notes",
                    models.TextField(
                        blank=True, null=True, verbose_name="Заметки барбера"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Ожидает подтверждения"),
                            ("confirmed", "Подтверждено"),
                            ("cancelled", "Отменено"),
                            ("completed", "Завершено"),
                            ("no_show", "Не явился"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="Статус",
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="Стоимость",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
                ),
                (
                    "barber",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bookings",
                        to="accounts.barberprofile",
                        verbose_name="Барбер",
                    ),
                ),
            ],
            options={
                "verbose_name": "Бронирование",
                "verbose_name_plural": "Бронирования",
                "ordering": ["-booking_date", "-booking_start_time"],
            },
        ),
        migrations.CreateModel(
            name="ScheduleOverride",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(verbose_name="Дата")),
                (
                    "override_type",
                    models.CharField(
                        choices=[
                            ("day_off", "Выходной день"),
                            ("custom_hours", "Изменение времени работы"),
                            ("custom_break", "Изменение перерыва"),
                        ],
                        default="day_off",
                        max_length=20,
                        verbose_name="Тип исключения",
                    ),
                ),
                (
                    "custom_start_time",
                    models.TimeField(
                        blank=True, null=True, verbose_name="Измененное время начала"
                    ),
                ),
                (
                    "custom_end_time",
                    models.TimeField(
                        blank=True, null=True, verbose_name="Измененное время окончания"
                    ),
                ),
                (
                    "custom_break_start",
                    models.TimeField(
                        blank=True,
                        null=True,
                        verbose_name="Измененное время начала перерыва",
                    ),
                ),
                (
                    "custom_break_end",
                    models.TimeField(
                        blank=True,
                        null=True,
                        verbose_name="Измененное время окончания перерыва",
                    ),
                ),
                (
                    "notes",
                    models.TextField(blank=True, null=True, verbose_name="Примечания"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
                ),
                (
                    "barber",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="schedule_overrides",
                        to="accounts.barberprofile",
                        verbose_name="Барбер",
                    ),
                ),
            ],
            options={
                "verbose_name": "Исключение в расписании",
                "verbose_name_plural": "Исключения в расписании",
                "ordering": ["date"],
            },
        ),
        migrations.CreateModel(
            name="TimeSlot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(verbose_name="Дата")),
                ("start_time", models.TimeField(verbose_name="Время начала")),
                ("end_time", models.TimeField(verbose_name="Время окончания")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("available", "Доступен"),
                            ("booked", "Забронирован"),
                            ("blocked", "Заблокирован"),
                        ],
                        default="available",
                        max_length=20,
                        verbose_name="Статус",
                    ),
                ),
                (
                    "is_auto_generated",
                    models.BooleanField(
                        default=True, verbose_name="Автоматически сгенерирован"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
                ),
                (
                    "barber",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="time_slots",
                        to="accounts.barberprofile",
                        verbose_name="Барбер",
                    ),
                ),
                (
                    "booking",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="slots",
                        to="schedule.booking",
                        verbose_name="Бронирование",
                    ),
                ),
            ],
            options={
                "verbose_name": "Временной слот",
                "verbose_name_plural": "Временные слоты",
                "ordering": ["date", "start_time"],
            },
        ),
        migrations.AddIndex(
            model_name="booking",
            index=models.Index(
                fields=["barber", "booking_date", "status"],
                name="schedule_bo_barber__e52457_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="booking",
            index=models.Index(
                fields=["booking_date", "status"], name="schedule_bo_booking_0c5256_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="booking",
            index=models.Index(
                fields=["client_phone"], name="schedule_bo_client__206073_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="scheduleoverride",
            unique_together={("barber", "date")},
        ),
        migrations.AddIndex(
            model_name="timeslot",
            index=models.Index(
                fields=["barber", "date", "status"],
                name="schedule_ti_barber__db4022_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="timeslot",
            index=models.Index(
                fields=["date", "status"], name="schedule_ti_date_b86488_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="timeslot",
            unique_together={("barber", "date", "start_time")},
        ),
    ]
